[package]
name = "vkr"
version = "0.0.7"
authors = ["Antonio Caggiano <info@antoniocaggiano.eu>"]
edition = "2018"
license = "MIT"

[dependencies]
vkr-core = { path = "../vkr-core" }
byteorder = "1.4.3"
memoffset = "0.7.1"

[build-dependencies]
vkr-pipe = { path = "../vkr-pipe" }
